### ISSUE TITLE
This library was not compiled in flutter latest stable version (1.7.8-hotfix.3)

### ISSUE THREAD

**Issue by jayden320** [KNightING/flutter_selectext#2]

**Comment by solokingjec** [comment]
^^^^^^^^^^^^^^
lib/utils/flutter_selectable_text.dart:262:9: Error: No named parameter with the name 'selectAll'.
        selectAll: false,
        ^^^^^^^^^
lib/utils/flutter_selectable_text.dart:348:9: Error: 'ToolbarOptions' isn't a type.
  final ToolbarOptions toolbarOptions;
        ^^^^^^^^^^^^^^
lib/utils/flutter_selectable_text.dart:481:43: Error: The getter 'shouldShowSelectionToolbar' isn't defined for the class '_SelectableTextSelectionGestureDetectorBuilder'.
 - '_SelectableTextSelectionGestureDetectorBuilder' is from 'package:biblejourney/utils/flutter_selectable_text.dart' ('lib/utils/flutter_selectable_text.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'shouldShowSelectionToolbar'.
    if (!_selectionGestureDetectorBuilder.shouldShowSelectionToolbar)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/utils/flutter_selectable_text.dart:558:9: Error: No named parameter with the name 'textWidthBasis'.
        textWidthBasis: widget.textWidthBasis ?? defaultTextStyle.textWidthBasis,
        ^^^^^^^^^^^^^^
file:///home/francis/flutter/packages/flutter/lib/src/widgets/editable_text.dart:273:3: Context: Found this candidate, but the arguments don't match.
  EditableText({
  ^
lib/utils/flutter_selectable_text.dart:597:47: Error: The method 'buildGestureDetector' isn't defined for the class '_SelectableTextSelectionGestureDetectorBuilder'.
 - '_SelectableTextSelectionGestureDetectorBuilder' is from 'package:biblejourney/utils/flutter_selectable_text.dart' ('lib/utils/flutter_selectable_text.dart').
Try correcting the name to the name of an existing method, or defining a method named 'buildGestureDetector'.
      child: _selectionGestureDetectorBuilder.buildGestureDetector(
                                              ^^^^^^^^^^^^^^^^^^^^
Compiler failed on /home/francis/IdeaProjects/wild-goose-publishing-flutter/lib/main.dart
Gradle task assembleDebug failed with exit code 1

**Comment by solokingjec** [comment]
![Screenshot from 2019-09-08 00-02-42](https://user-images.githubusercontent.com/6312641/64480196-0fcae700-d1cc-11e9-9c67-e483bca621f1.png)

**Comment by solokingjec** [comment]
![Screenshot from 2019-09-08 00-03-56](https://user-images.githubusercontent.com/6312641/64480215-312bd300-d1cc-11e9-9802-3c494a9b0b50.png)
